### ISSUE TITLE
Train routines to train new model with different face detectors

### ISSUE THREAD

**Issue by inspirit** [delphifirst/FaceX#1]
Hi, first of all thanx for sharing your project!

I was wondering if u can also share classes used for training? because with out them its impossible to train different models using different dataset or different face-detector for example.

looking forward to hear from you!

**Comment by delphifirst** [comment]
I'm glad that you are interested in my project. I will add the training code soon.

**Comment by inspirit** [comment]
great! any estimate when you can push it?
really need to do the tests with different datasets and initial parameters.
thanks!

**Comment by kingvision** [comment]
hi, l like your sharing code. it help me learn a lot.
a few days ago ,  i  red the cvpr 2014 paper: 3000fps face alignment. i donot how to implemen t the paper by myself. can you give  me  some ideas?  would you implement the  paper and share?
thanks

**Comment by delphifirst** [comment]
It seems here (https://github.com/jwyang/face-alignment) is an implementation of that paper. However, I have not checked whether it works.

**Comment by kingvision** [comment]
my mean is to implement the 3000fps paper using c++.  i got some confused .

**Comment by delphifirst** [comment]
I'm sorry but currently I'm a little busy. Maybe I can implement it later.
