### ISSUE TITLE
optimization proposal

### ISSUE THREAD

**Issue by berak** [delphifirst/FaceX#10]
hello, nice work !

the detection spends almost all of its time in Regresseor::Apply() [here](https://github.com/delphifirst/FaceX/blob/master/FaceX/regressor.cpp#L60)

replacing the  for loop and the multiple matrix operations with less, and larger ones reduced execution time by a good half.

```
cv::Mat result_mat;                    // no initialization
Mat c(coeffs),c2;                      // c2 will have same shape as base_
c = c.reshape(1,1);                    // we need a row vec
repeat(c, base_.rows, 1, c2);          // the 1st row of coeffs all the way down
Mat m2;
multiply(base_, c2, m2);               // giant per element mul
reduce(m2, result_mat, 1, REDUCE_SUM); // sum up the cols into result_mat
```

**Comment by delphifirst** [comment]
Thank you very much.

I have got your point, and changed the for-loop into matrix multiplication. I get about 4x speed-up for the test.jpg in FaceX. The code has already been updated.

**Comment by berak** [comment]
thank you very much for writing this in the 1st place !

(i'll just close the issue ?)
