### ISSUE TITLE
 How should I obtain a face area when training on a helen dataset?

### ISSUE THREAD

**Issue by sunnythree** [delphifirst/FaceX#12]
The helen dataset does not have a face area. How should I obtain a face area when training on a helen dataset?

**Comment by delphifirst** [comment]
You can generate a face area according to landmarks. For example the topmost landmark become face top...

**Comment by sunnythree** [comment]
Thanks, I will try it. I am concerned that the face area thus generated is too perfect. In actual use, the detected face area and the face area thus generated are so different that the result is inaccurate.

**Comment by delphifirst** [comment]
Yes, you have to make the generated face area look like the detected face area as much as possible.

**Comment by sunnythree** [comment]
I got it,thanks a lot
