### ISSUE TITLE
Procrustes analysis question

### ISSUE THREAD

**Issue by kingvision** [delphifirst/FaceX#2]
Hi, 
     thank you for your sharing code.
     i have a question about procrustes transform. The function 
     Transform Procrustes(const vectorcv::Point2d &x, const vectorcv::Point2d &y)
     i do not understand the solution why  equal to A.inv() \* b ？why the Matirx A is so ?
thanks!

**Comment by delphifirst** [comment]
Procrustes Analysis is a well-studied subject. This code is based on the APPENDIX A of this paper:

Cootes T F, Taylor C J, Cooper D H, et al. Active shape models-their training and application[J]. Computer vision and image understanding, 1995, 61(1): 38-59.

Actually, I also don't understand how it works. I just follow that paper, and happily, it just works.
