### ISSUE TITLE
why need a face rect?

### ISSUE THREAD

**Issue by kingvision** [delphifirst/FaceX#6]
hi, why need a face rect in the train processing?
if a sample 's landmarks are out of the face rect, what it will happen?
thanks

**Comment by delphifirst** [comment]
face rect is used in MapShape. For example, when you've got the face rect in one image, and you want to give an initial guess of landmarks for it, you will need it.

Nothing special will happen if a sample's landmarks are out of the face rect. face rect is just used for normalization.

Actually, if the training data you've got only have landmarks, you can estimate face rect according to the landmarks.
