### ISSUE TITLE
kmeans question

### ISSUE THREAD

**Issue by kingvision** [delphifirst/FaceX#7]
Hi:
   as you said that the face rect is used by Mapshape function. That is ok if some landmarks are out of the face rect. But it is error when i use some samples that have some landmarks  being out of the sample's face rect. where is the error is in the function cv::kmenas.

why?
thanks

**Comment by delphifirst** [comment]
I did some tests, and found there was no problem even if some landmarks were out of the face rect. Is your landmarks not only out of the face rect, but also out of the image?

**Comment by kingvision** [comment]
ok.  thanks i think i made a mistake
